---
- hosts: webserver
  gather_facts: yes
  
  tasks: 
  - name: Update apache version - yum
    yum: name=httpd state=present
    when: ansible_pkg_msg == 'yum'
    notify: restart httpd
    
  - name: Update apache version - apt
    apt: name=apache2 state=present update_cache=yes
    when: ansible_pkg_msg == 'apt'
    notify: restart apache2
    
  handlers:
  - name: restart httpd
    service: name=httpd state=restarted
  handlers:
  - name: restart apache2
    service: name=apache2 state=restarted
    