---
- name: Install Nginx,PHP-FPM and Wordpress
  hosts: webserver
  remote_user: root

  roles:
    - role: common
    - role: nginx
      tags: ["nginx"]
    - role: php
      tags: ["php"]
    - role: wordpress
      tags: ["wp"]
