#1、安装JDK
#2、下载tomcat包
#3、解压tomcat
#4、启动tomcat
---
- hosts: webserver
  gather_facts: no
  vars:
    tomcat_version: 8.5.54
	tomcat_install_dir: /usr/local/
  tasks: 
    - name: Install jdk1.8
	  yum: name=java-1.8.0-openjdk state=present
	
	- name: Download tomcat
      get_url: url=http://mirrors.hust.edu.cn/apache/tomcat/tomcat-8/v{{tomcat_version}}/bin/apache-tomcat-{{tomcat_version}}.tar.gz dest=/tmp
      
    - name: Unarchive tomcat-{{tomcat_version}}.tar.gz
      unarchive: 
        src: /tmp/apache-tomcat-{{tomcat_version}}.tar.gz
        dest: "tomcat_install_dir"
        copy: no
        
    - name: Start tomcat
      shell: cd {{tomcat_install_dir}} &&
             mv apache-tomcat-{{tomcat_version}} tomcat8 &&
             cd tomcat8/bin && nohup ./startup.up &